### ISSUE TITLE
Drop support for Python 3.8

### ISSUE THREAD

**Issue by jmgate** [sandialabs/staged-script#155]
## Tasks
* [x] Update `pyproject.toml` to reflect the change.
* [x] Update the badge in `README.md` and `doc/source/index.rst`.
* [x] Update the CI file.
* [x] Use the type-hinting provided out of the box in 3.9.
* [x] See if there are any other 3.9 features to use within the code.
