### ISSUE TITLE
Rework run() arguments

### ISSUE THREAD

**Issue by jmgate** [sandialabs/staged-script#6]
# Tasks
- [ ] Revert 520b68e18c7e492ecec529d4d0a64e2f04b180af.
- [ ] Switch the first argument to the `run()` method from a string to a list of strings to protect against command injection in the shell.
- [ ] Make any associated changes to bring everything in sync.

> **Note:**  This will be a breaking change, but it will be worthwhile to remove the possibility of this unsafe behavior.

**Comment by jmgate** [comment]
When we do this, we can remove the `.bandit` file in the repository root, and adjust `pyproject.toml` such that `S604` is not longer ignored in the examples.
